CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(64) NOT NULL UNIQUE);
CREATE TABLE suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(200) NOT NULL, status varchar(32) NOT NULL DEFAULT 'ACTIVE', category varchar(100), location varchar(160), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username varchar(100) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL, display_name varchar(160) NOT NULL, email varchar(255) NOT NULL UNIQUE, role_id uuid NOT NULL REFERENCES roles(id), supplier_id uuid REFERENCES suppliers(id), is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE user_suppliers (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, supplier_id uuid NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE, PRIMARY KEY (user_id, supplier_id));
CREATE TABLE vehicle_models (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name varchar(160) NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE components (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), part_number varchar(100) NOT NULL UNIQUE, name varchar(200) NOT NULL, category varchar(100), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE supplier_components (supplier_id uuid NOT NULL REFERENCES suppliers(id) ON DELETE CASCADE, component_id uuid NOT NULL REFERENCES components(id) ON DELETE CASCADE, capacity integer NOT NULL DEFAULT 0, quality_score numeric(5,2), PRIMARY KEY (supplier_id, component_id));
CREATE TABLE supplier_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), supplier_id uuid NOT NULL REFERENCES suppliers(id), status varchar(32) NOT NULL, reason text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE bom_headers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), vehicle_model_id uuid NOT NULL REFERENCES vehicle_models(id), revision varchar(32) NOT NULL, status varchar(32) NOT NULL DEFAULT 'ACTIVE', UNIQUE (vehicle_model_id, revision));
CREATE TABLE bom_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), bom_header_id uuid NOT NULL REFERENCES bom_headers(id) ON DELETE CASCADE, component_id uuid NOT NULL REFERENCES components(id), quantity integer NOT NULL CHECK (quantity > 0));
CREATE TABLE inventory (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), component_id uuid NOT NULL REFERENCES components(id), location varchar(160) NOT NULL, quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (component_id, location));
CREATE TABLE customer_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), external_reference varchar(100) NOT NULL UNIQUE, status varchar(32) NOT NULL, due_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE customer_order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), customer_order_id uuid NOT NULL REFERENCES customer_orders(id) ON DELETE CASCADE, component_id uuid NOT NULL REFERENCES components(id), quantity integer NOT NULL CHECK (quantity > 0));
CREATE TABLE planning_requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), component_name varchar(200) NOT NULL, required_quantity integer NOT NULL CHECK (required_quantity > 0), current_inventory integer NOT NULL DEFAULT 0 CHECK (current_inventory >= 0), required_delivery_date timestamptz, priority varchar(32) NOT NULL DEFAULT 'MEDIUM', status varchar(32) NOT NULL DEFAULT 'NEW');
CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), action varchar(64) NOT NULL, entity_type varchar(64) NOT NULL, entity_id uuid NOT NULL, old_values jsonb, new_values jsonb, created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS execution_id uuid;
CREATE INDEX IF NOT EXISTS ix_audit_execution ON audit_logs(execution_id);

CREATE TABLE rfqs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requirement_id uuid, created_by uuid NOT NULL REFERENCES users(id), status varchar(32) NOT NULL DEFAULT 'DRAFT', release_date timestamptz, quotation_deadline timestamptz NOT NULL, required_delivery_date timestamptz NOT NULL, evaluation_policy text NOT NULL, expected_supplier_count integer NOT NULL CHECK (expected_supplier_count > 0), minimum_valid_quotation_count integer NOT NULL CHECK (minimum_valid_quotation_count > 0), created_at timestamptz NOT NULL DEFAULT now(), CHECK (minimum_valid_quotation_count <= expected_supplier_count));
CREATE TABLE rfq_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id) ON DELETE CASCADE, component_id uuid REFERENCES components(id), description text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0));
CREATE TABLE rfq_suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id) ON DELETE CASCADE, supplier_id uuid NOT NULL REFERENCES suppliers(id), response_status varchar(32) NOT NULL DEFAULT 'PENDING' CHECK (response_status IN ('PENDING','VIEWED','RESPONDED','LATE','NO_RESPONSE','WITHDRAWN')), sent_at timestamptz, viewed_at timestamptz, responded_at timestamptz, UNIQUE (rfq_id, supplier_id));
CREATE TABLE quotations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id), supplier_id uuid NOT NULL REFERENCES suppliers(id), version integer NOT NULL CHECK (version > 0), unit_price numeric(14,4) NOT NULL CHECK (unit_price > 0), total_price numeric(18,2) NOT NULL CHECK (total_price > 0), quantity integer NOT NULL CHECK (quantity > 0), available_quantity integer NOT NULL CHECK (available_quantity >= 0), delivery_at timestamptz NOT NULL, payment_terms varchar(120), warranty_quality text, additional_notes text, submitted_at timestamptz NOT NULL DEFAULT now(), status varchar(32) NOT NULL DEFAULT 'SUBMITTED', supersedes_id uuid REFERENCES quotations(id), UNIQUE (rfq_id, supplier_id, version));
CREATE UNIQUE INDEX uq_current_quotation ON quotations(rfq_id, supplier_id) WHERE status <> 'SUPERSEDED';
CREATE TABLE negotiations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id), quotation_id uuid NOT NULL REFERENCES quotations(id), supplier_id uuid NOT NULL REFERENCES suppliers(id), status varchar(32) NOT NULL DEFAULT 'OPEN', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approvals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id), quotation_id uuid NOT NULL REFERENCES quotations(id), requested_by uuid NOT NULL REFERENCES users(id), status varchar(32) NOT NULL DEFAULT 'PENDING', decision_reason text, decided_at timestamptz);
CREATE TABLE procurement_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), event_type varchar(64) NOT NULL, priority varchar(16) NOT NULL DEFAULT 'MEDIUM', source_user_id uuid REFERENCES users(id), rfq_id uuid REFERENCES rfqs(id), component_id uuid, supplier_id uuid REFERENCES suppliers(id), context jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE workflow_executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workflow_type varchar(64) NOT NULL, event_type varchar(64) NOT NULL, parent_execution_id uuid REFERENCES workflow_executions(id), status varchar(32) NOT NULL DEFAULT 'QUEUED', requested_by uuid REFERENCES users(id), rfq_id uuid REFERENCES rfqs(id), component_id uuid, supplier_id uuid REFERENCES suppliers(id), sns_workflow_id varchar(255), sns_execution_id varchar(255) UNIQUE, input_payload jsonb NOT NULL DEFAULT '{}'::jsonb, output_payload jsonb, error_message text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX ix_execution_lineage ON workflow_executions(parent_execution_id);
CREATE TABLE decision_recommendations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), rfq_id uuid NOT NULL REFERENCES rfqs(id), execution_id uuid REFERENCES workflow_executions(id), status varchar(32) NOT NULL DEFAULT 'PENDING_HUMAN_REVIEW', recommendation jsonb NOT NULL, deterministic_result jsonb NOT NULL, explanation text, human_decision varchar(32), human_notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE negotiation_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), negotiation_id uuid NOT NULL REFERENCES negotiations(id) ON DELETE CASCADE, sender_type varchar(32) NOT NULL, message_type varchar(32) NOT NULL, content text NOT NULL, authorized_by uuid REFERENCES users(id), execution_id uuid REFERENCES workflow_executions(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), supplier_id uuid NOT NULL REFERENCES suppliers(id), rfq_id uuid NOT NULL REFERENCES rfqs(id), quotation_id uuid NOT NULL REFERENCES quotations(id), created_by uuid NOT NULL REFERENCES users(id), status varchar(32) NOT NULL DEFAULT 'DRAFT', acknowledged_at timestamptz, acknowledgement_notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE purchase_order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE, description text NOT NULL, quantity integer NOT NULL CHECK (quantity > 0), unit_price numeric(14,4) NOT NULL CHECK (unit_price > 0));

CREATE INDEX ix_rfq_status ON rfqs(status);
CREATE INDEX ix_rfq_supplier_status ON rfq_suppliers(supplier_id, response_status);
CREATE INDEX ix_quotations_rfq_status ON quotations(rfq_id, status);
CREATE INDEX ix_audit_entity ON audit_logs(entity_type, entity_id);

INSERT INTO roles (name) VALUES ('PROCUREMENT_MANAGER'), ('SUPPLIER'), ('FINANCE_APPROVER') ON CONFLICT (name) DO NOTHING;
